/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file    app_netxduo.c
  * @author  MCD Application Team
  * @brief   NetXDuo applicative file
  ******************************************************************************
    * @attention
  *
  * Copyright (c) 2021 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */
/* USER CODE END Header */

/* Includes ------------------------------------------------------------------*/
#include "app_netxduo.h"

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */
#include "app_azure_rtos.h"
/* USER CODE END Includes */

/* Private typedef -----------------------------------------------------------*/
/* USER CODE BEGIN PTD */

/* USER CODE END PTD */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */

/* USER CODE END PD */

/* Private macro -------------------------------------------------------------*/
/* USER CODE BEGIN PM */
static VOID App_Main_Thread_Entry(ULONG thread_input);
static VOID App_HTTP_Thread_Entry(ULONG thread_input);
static VOID ip_address_change_notify_callback(NX_IP *ip_instance, VOID *ptr);
static UINT tls_setup_callback(NX_WEB_HTTP_CLIENT *client_ptr, NX_SECURE_TLS_SESSION *tls_session);
/* USER CODE END PM */

/* Private variables ---------------------------------------------------------*/
/* USER CODE BEGIN PV */
TX_THREAD AppMainThread;
TX_THREAD AppHTTPThread;

TX_SEMAPHORE Semaphore;

NX_PACKET_POOL AppPool;

ULONG IpAddress;
ULONG NetMask;
NX_IP IpInstance;

NX_DHCP DHCPClient;
NX_WEB_HTTP_CLIENT HttpClient;
CHAR *pointer;

/* TLS session setup (tls_setup_callback, below). The ciphersuite table
 * (nx_crypto_tls_ciphers, no ECC/AEAD -- see NetXDuo/App/nx_secure_user.h)
 * offers exactly TLS_RSA_WITH_AES_{128,256}_CBC_SHA256, TLS 1.2, static-RSA
 * key exchange: the server encrypts nothing with its private key except to
 * *decrypt* the client's RSA-encrypted pre-master secret -- about as
 * textbook a TLS handshake as it gets. */
extern const NX_SECURE_TLS_CRYPTO nx_crypto_tls_ciphers;

/* Sized with nx_secure_tls_session_metadata_size_calculate(&nx_crypto_tls_ciphers, ...)
 * against this exact ciphersuite table -- see ST's own Nx_MQTT_Client
 * reference project, which uses the identical table on the identical
 * target. Working scratch space for the crypto operations themselves
 * (RSA/AES/SHA), not certificate or handshake-message storage. */
static CHAR crypto_metadata_client[11600];

/* TLS record reassembly buffer -- big enough for our ~800-byte self-signed
 * leaf cert plus handshake overhead with headroom to spare. */
static UCHAR tls_packet_buffer[4000];

/* The trusted root: our self-signed cert (NetXDuo/App/https_ca_cert.h,
 * generated by tools/gen_https_cert.sh), added to the TLS session's
 * trusted store every connection in tls_setup_callback. Since it's
 * self-signed, this trusted copy and the leaf the server presents are
 * byte-for-byte the same certificate -- there's no separate CA above it. */
static NX_SECURE_X509_CERT trusted_certificate;

/* Scratch space the TLS session parses the server's presented certificate
 * chain into during the handshake (leaf + issuer -- even though our chain
 * is only one cert deep, nx_secure_tls_remote_certificate_allocate still
 * expects both slots set up). */
static NX_SECURE_X509_CERT remote_certificate;
static NX_SECURE_X509_CERT remote_issuer;
static UCHAR remote_cert_buffer[2000];
static UCHAR remote_issuer_buffer[2000];
/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
/* USER CODE BEGIN PFP */

/* USER CODE END PFP */

/**
  * @brief  Application NetXDuo Initialization.
  * @param memory_ptr: memory pointer
  * @retval int
  */
UINT MX_NetXDuo_Init(VOID *memory_ptr)
{
  UINT ret = NX_SUCCESS;
  TX_BYTE_POOL *byte_pool = (TX_BYTE_POOL*)memory_ptr;

   /* USER CODE BEGIN App_NetXDuo_MEM_POOL */

  /* USER CODE END App_NetXDuo_MEM_POOL */
  /* USER CODE BEGIN 0 */

  /* USER CODE END 0 */

  /* USER CODE BEGIN MX_NetXDuo_Init */
#if (USE_STATIC_ALLOCATION == 1)    
  printf("Nx_UDP_Echo_Client_App started..\n");

  /* Initialize the NetX system. */
  nx_system_initialize();
  
  /* Allocate the memory for packet_pool.  */
  if (tx_byte_allocate(byte_pool, (VOID **) &pointer,  NX_PACKET_POOL_SIZE, TX_NO_WAIT) != TX_SUCCESS)
  {
    return TX_POOL_ERROR;
  }  
  
  /* Create the Packet pool to be used for packet allocation */
  ret = nx_packet_pool_create(&AppPool, "Main Packet Pool", PAYLOAD_SIZE, pointer, NX_PACKET_POOL_SIZE);
  
  if (ret != NX_SUCCESS)
  {
    return NX_NOT_ENABLED;
  }
  
  /* Allocate the memory for Ip_Instance */
  if (tx_byte_allocate(byte_pool, (VOID **) &pointer,   2 * DEFAULT_MEMORY_SIZE, TX_NO_WAIT) != TX_SUCCESS)
  {
    return TX_POOL_ERROR;
  }
  
  /* Create the main NX_IP instance */
  ret = nx_ip_create(&IpInstance, "Main Ip instance", NULL_ADDRESS, NULL_ADDRESS, &AppPool, nx_driver_emw3080_entry,
                     pointer, 2 * DEFAULT_MEMORY_SIZE, DEFAULT_PRIORITY);
  
  if (ret != NX_SUCCESS)
  {
    return NX_NOT_ENABLED;
  }
  
  /* Allocate the memory for ARP */
  if (tx_byte_allocate(byte_pool, (VOID **) &pointer, DEFAULT_MEMORY_SIZE, TX_NO_WAIT) != TX_SUCCESS)
  {
    return TX_POOL_ERROR;
  }
  
  /*  Enable the ARP protocol and provide the ARP cache size for the IP instance */
  ret = nx_arp_enable(&IpInstance, (VOID *)pointer, DEFAULT_MEMORY_SIZE);
  
  if (ret != NX_SUCCESS)
  {
    return NX_NOT_ENABLED;
  }
  
  /* Enable the ICMP */
  ret = nx_icmp_enable(&IpInstance);
  
  if (ret != NX_SUCCESS)
  {
    return NX_NOT_ENABLED;
  }
  
  /* Enable the UDP protocol required for  DHCP communication */
  ret = nx_udp_enable(&IpInstance);

  /* Enable the TCP protocol, required by the HTTP client */
  ret = nx_tcp_enable(&IpInstance);

  if (ret != NX_SUCCESS)
  {
    return NX_NOT_ENABLED;
  }

  /* Allocate the memory for main thread   */
  if (tx_byte_allocate(byte_pool, (VOID **) &pointer,2 *  DEFAULT_MEMORY_SIZE, TX_NO_WAIT) != TX_SUCCESS)
  {
    return TX_POOL_ERROR;
  }  
  
  /* Create the main thread */
  ret = tx_thread_create(&AppMainThread, "App Main thread", App_Main_Thread_Entry, 0, pointer, 2 * DEFAULT_MEMORY_SIZE,
                         APP_THREAD_PRIORITY, APP_THREAD_PRIORITY, TX_NO_TIME_SLICE, TX_AUTO_START);
  
  if (ret != TX_SUCCESS)
  {
    return NX_NOT_ENABLED;
  }
  
  /* Allocate the memory for HTTP client thread   */
  if (tx_byte_allocate(byte_pool, (VOID **) &pointer,2 *  DEFAULT_MEMORY_SIZE, TX_NO_WAIT) != TX_SUCCESS)
  {
    return TX_POOL_ERROR;
  }

  /* create the HTTP client thread */
  ret = tx_thread_create(&AppHTTPThread, "App HTTP Thread", App_HTTP_Thread_Entry, 0, pointer, 2 * DEFAULT_MEMORY_SIZE,
                         APP_THREAD_PRIORITY, APP_THREAD_PRIORITY, TX_NO_TIME_SLICE, TX_DONT_START);
  
  if (ret != TX_SUCCESS)
  {
    return NX_NOT_ENABLED;
  }
  
  /* create the DHCP client */
  ret = nx_dhcp_create(&DHCPClient, &IpInstance, "DHCP Client");
  
  if (ret != NX_SUCCESS)
  {
    return NX_NOT_ENABLED;
  }
  
  /* set DHCP notification callback  */
  tx_semaphore_create(&Semaphore, "App Semaphore", 0);
#endif  
  /* USER CODE END MX_NetXDuo_Init */

  return ret;
}

/* USER CODE BEGIN 1 */
/**
* @brief  ip address change callback.
* @param ip_instance: NX_IP instance
* @param ptr: user data
* @retval none
*/
static VOID ip_address_change_notify_callback(NX_IP *ip_instance, VOID *ptr)
{
  /* release the semaphore as soon as an IP address is available */
  tx_semaphore_put(&Semaphore);
}

/**
* @brief  Main thread entry.
* @param thread_input: ULONG user argument used by the thread entry
* @retval none
*/
static VOID App_Main_Thread_Entry(ULONG thread_input)
{
  UINT ret;
  
  /* register the IP address change callback */
  ret = nx_ip_address_change_notify(&IpInstance, ip_address_change_notify_callback, NULL);
  if (ret != NX_SUCCESS)
  {
    Error_Handler();
  }
  
  /* start the DHCP client */
  ret = nx_dhcp_start(&DHCPClient);
  if (ret != NX_SUCCESS)
  {
    Error_Handler();
  }

  /* wait until an IP address is ready */
  if(tx_semaphore_get(&Semaphore, TX_WAIT_FOREVER) != TX_SUCCESS)
  {
    Error_Handler();
  }
  /* get IP address */
  ret = nx_ip_address_get(&IpInstance, &IpAddress, &NetMask);
  
  /* print the IP address and the net mask */
  PRINT_IP_ADDRESS(IpAddress);

  if (ret != TX_SUCCESS)
  {
    Error_Handler();
  }
  /* the network is correctly initialized, start the HTTP thread */
  tx_thread_resume(&AppHTTPThread);

  /* this thread is not needed any more, we relinquish it */
  tx_thread_relinquish();

  return;
}

/* Sets up one TLS session for the HTTP client -- passed as the tls_setup
 * callback to nx_web_http_client_post_secure_start(), which invokes it
 * itself right before the handshake starts. Called fresh on every
 * connection (App_HTTP_Thread_Entry creates/deletes the HTTP client each
 * poll), matching the lifecycle both ST's demo_netxduo_https.c and the
 * Nx_MQTT_Client reference project use.
 *
 * NOTE on scope: this validates the certificate *chain* the server
 * presents (its signature must trace back to trusted_certificate below --
 * here, be byte-identical to it, since it's self-signed) but does not
 * check the server's hostname/IP against the certificate's CN/SAN --
 * nx_web_http_client has no hook for that. So "validating the server"
 * here means "cryptographically verifying we got the exact cert we
 * trust," not "matches the URL we asked for" -- a real, common
 * simplification in embedded TLS clients, not a corner cut silently. */
static UINT tls_setup_callback(NX_WEB_HTTP_CLIENT *client_ptr, NX_SECURE_TLS_SESSION *tls_session)
{
    UINT ret;

    NX_PARAMETER_NOT_USED(client_ptr);

    ret = nx_secure_tls_session_create(tls_session, &nx_crypto_tls_ciphers,
                                       crypto_metadata_client, sizeof(crypto_metadata_client));
    if (ret != NX_SUCCESS)
    {
        printf("TLS session create failed: 0x%02X\r\n", ret);
        return(ret);
    }

    ret = nx_secure_tls_session_packet_buffer_set(tls_session, tls_packet_buffer,
                                                  sizeof(tls_packet_buffer));
    if (ret != NX_SUCCESS)
    {
        printf("TLS packet buffer set failed: 0x%02X\r\n", ret);
        return(ret);
    }

    /* Trust anchor: our self-signed cert, embedded at build time
     * (https_ca_cert.h, generated by tools/gen_https_cert.sh). No private
     * key here -- we're only ever verifying a signature with it, never
     * signing anything, so NX_SECURE_X509_KEY_TYPE_NONE. */
    ret = nx_secure_x509_certificate_initialize(&trusted_certificate,
                                                (UCHAR *)https_ca_cert_der, https_ca_cert_der_len,
                                                NX_NULL, 0, NULL, 0, NX_SECURE_X509_KEY_TYPE_NONE);
    if (ret != NX_SUCCESS)
    {
        printf("Trusted certificate init failed: 0x%02X\r\n", ret);
        return(ret);
    }

    ret = nx_secure_tls_trusted_certificate_add(tls_session, &trusted_certificate);
    if (ret != NX_SUCCESS)
    {
        printf("Trusted certificate add failed: 0x%02X\r\n", ret);
        return(ret);
    }

    /* Scratch space for the certificate(s) the server actually sends
     * during the handshake, which TLS parses into these before running
     * the check against trusted_certificate above. */
    ret = nx_secure_tls_remote_certificate_allocate(tls_session, &remote_certificate,
                                                    remote_cert_buffer, sizeof(remote_cert_buffer));
    if (ret != NX_SUCCESS)
    {
        printf("Remote certificate allocate failed: 0x%02X\r\n", ret);
        return(ret);
    }

    ret = nx_secure_tls_remote_certificate_allocate(tls_session, &remote_issuer,
                                                    remote_issuer_buffer, sizeof(remote_issuer_buffer));
    if (ret != NX_SUCCESS)
    {
        printf("Remote issuer certificate allocate failed: 0x%02X\r\n", ret);
        return(ret);
    }

    return(NX_SUCCESS);
}

/* Periodic HTTPS POST client: every HTTP_POLL_PERIOD_SEC seconds, opens a
 * fresh TLS connection to HTTP_SERVER_ADDRESS:HTTP_SERVER_HTTPS_PORT and
 * POSTs an incrementing decimal counter as the request body to
 * HTTP_RESOURCE, prints the (decrypted) response body, and tears the
 * client back down — one clean create/handshake/POST/delete cycle per
 * request, matching the lifecycle NetX Duo's own HTTP client POST sample
 * (netx_web_post_basic_test.c) uses: post_secure_start (runs the TLS
 * handshake via tls_setup_callback above, then sends headers +
 * Content-Length over the now-encrypted connection) ->
 * request_packet_allocate -> nx_packet_data_append (fills the body) ->
 * put_packet (encrypts and sends it). */
static VOID App_HTTP_Thread_Entry(ULONG thread_input)
{
    UINT        ret;
    UINT        get_status;
    NXD_ADDRESS server_ip_address;
    NX_PACKET  *send_packet;
    NX_PACKET  *receive_packet;
    UCHAR       receive_buffer[256];
    ULONG       bytes;
    ULONG       counter = 0;
    CHAR        counter_str[16];
    UINT        counter_len;

    TX_PARAMETER_NOT_USED(thread_input);

    server_ip_address.nxd_ip_version = NX_IP_VERSION_V4;
    server_ip_address.nxd_ip_address.v4 = HTTP_SERVER_ADDRESS;

    printf("HTTPS POST client ready. Target https://%u.%u.%u.%u:%d%s\r\n",
           (unsigned)((HTTP_SERVER_ADDRESS >> 24) & 0xFF),
           (unsigned)((HTTP_SERVER_ADDRESS >> 16) & 0xFF),
           (unsigned)((HTTP_SERVER_ADDRESS >> 8) & 0xFF),
           (unsigned)(HTTP_SERVER_ADDRESS & 0xFF),
           HTTP_SERVER_HTTPS_PORT, HTTP_RESOURCE);

    while (1)
    {
        ret = nx_web_http_client_create(&HttpClient, "HTTP Client", &IpInstance, &AppPool, 1536);
        if (ret != NX_SUCCESS)
        {
            printf("HTTP client create failed: 0x%02X\r\n", ret);
            tx_thread_sleep(HTTP_POLL_PERIOD_SEC * TX_TIMER_TICKS_PER_SECOND);
            continue;
        }

        counter_len = (UINT)snprintf(counter_str, sizeof(counter_str), "%lu", counter);

        /* post_secure_start runs the TLS handshake (via tls_setup_callback
         * above) and then, over the now-encrypted connection, sends the
         * request line + headers (including Content-Length: counter_len
         * from the total_bytes argument below); the body itself goes out
         * separately via put_packet. */
        ret = nx_web_http_client_post_secure_start(&HttpClient, &server_ip_address, HTTP_SERVER_HTTPS_PORT,
                                                    HTTP_RESOURCE, HTTP_SERVER_HOST, NX_NULL, NX_NULL,
                                                    counter_len, tls_setup_callback, 5 * NX_IP_PERIODIC_RATE);
        if (ret != NX_SUCCESS)
        {
            printf("POST (TLS) start failed: 0x%02X\r\n", ret);
        }
        else
        {
            ret = nx_web_http_client_request_packet_allocate(&HttpClient, &send_packet,
                                                              5 * NX_IP_PERIODIC_RATE);
            if (ret != NX_SUCCESS)
            {
                printf("POST packet allocate failed: 0x%02X\r\n", ret);
            }
            else
            {
                nx_packet_data_append(send_packet, counter_str, counter_len, &AppPool,
                                      5 * NX_IP_PERIODIC_RATE);

                ret = nx_web_http_client_put_packet(&HttpClient, send_packet,
                                                    5 * NX_IP_PERIODIC_RATE);
                if (ret != NX_SUCCESS)
                {
                    printf("POST send failed: 0x%02X\r\n", ret);
                    nx_packet_release(send_packet);
                }
                else
                {
                    /* Drain and print the response body, one packet at a time. */
                    get_status = NX_SUCCESS;
                    while (get_status != NX_WEB_HTTP_GET_DONE)
                    {
                        get_status = nx_web_http_client_response_body_get(&HttpClient, &receive_packet,
                                                                           5 * NX_IP_PERIODIC_RATE);

                        if (get_status != NX_SUCCESS && get_status != NX_WEB_HTTP_GET_DONE)
                        {
                            printf("POST response read failed: 0x%02X\r\n", get_status);
                            break;
                        }

                        bytes = 0;
                        nx_packet_data_extract_offset(receive_packet, 0, receive_buffer,
                                                      sizeof(receive_buffer) - 1, &bytes);
                        receive_buffer[bytes] = 0;
                        printf("POST %s <- %s -> %s\r\n", HTTP_RESOURCE, counter_str,
                               (char *)receive_buffer);
                        nx_packet_release(receive_packet);
                    }

                    HAL_GPIO_TogglePin(LED_GREEN_GPIO_Port, LED_GREEN_Pin);
                    counter++;
                }
            }
        }

        nx_web_http_client_delete(&HttpClient);

        tx_thread_sleep(HTTP_POLL_PERIOD_SEC * TX_TIMER_TICKS_PER_SECOND);
    }
}
/* USER CODE END 1 */
