#!/usr/bin/env bash
# gen_https_cert.sh -- (re)generate the self-signed cert/key pair
# tools/http_server.py serves, and the C header the board embeds as its
# sole trusted root (NetXDuo/App/https_ca_cert.h, included from
# app_netxduo.c's tls_setup_callback).
#
# Since the cert is self-signed and the board has no live clock (no RTC/
# SNTP wired up -- see app_netxduo.c comments), it's issued with a 10-year
# validity window so wall-clock drift never matters in practice; NetX
# Secure's chain-of-trust check here amounts to "is this exactly the cert
# I was given," not real-world CA-style trust.
#
# Usage: tools/gen_https_cert.sh [server-ip]   (default: 10.198.244.16,
#        must match HTTP_SERVER_ADDRESS / HTTP_SERVER_HOST in
#        NetXDuo/App/app_netxduo.h -- rerun this after changing either)
set -euo pipefail

SERVER_IP="${1:-10.198.244.16}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CERT_DIR="$HERE/certs"
HEADER="$HERE/../NetXDuo/App/https_ca_cert.h"

mkdir -p "$CERT_DIR"

echo "Generating self-signed cert for IP:$SERVER_IP (10-year validity)..."
openssl req -x509 -newkey rsa:2048 -nodes -days 3650 \
    -keyout "$CERT_DIR/server.key" -out "$CERT_DIR/server.crt" \
    -subj "/CN=$SERVER_IP" \
    -addext "subjectAltName=IP:$SERVER_IP"

openssl x509 -in "$CERT_DIR/server.crt" -outform DER -out "$CERT_DIR/server.der"

echo "Writing $HEADER ..."
python3 - "$CERT_DIR/server.der" "$HEADER" "$SERVER_IP" << 'PYEOF'
import sys, datetime

der_path, header_path, server_ip = sys.argv[1], sys.argv[2], sys.argv[3]
data = open(der_path, "rb").read()

lines = []
for i in range(0, len(data), 12):
    chunk = data[i:i + 12]
    lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")

header = f"""/**
 * https_ca_cert.h -- self-signed root the board trusts for HTTPS.
 *
 * Generated by tools/gen_https_cert.sh -- DO NOT hand-edit, rerun the
 * script instead (e.g. after HTTP_SERVER_ADDRESS changes, or once this
 * cert's 10-year validity window is up).
 *
 * Subject/Issuer: CN={server_ip} (self-signed -- issuer == subject).
 * Generated: {datetime.date.today().isoformat()}
 *
 * This is the exact DER encoding of tools/certs/server.crt, the cert
 * tools/http_server.py presents over TLS. app_netxduo.c's
 * tls_setup_callback() adds it to the TLS session's trusted store via
 * nx_secure_x509_certificate_initialize() + nx_secure_tls_trusted_certificate_add() --
 * NetX Secure accepts the server's cert only because it is byte-for-byte
 * this one (self-signed leaf trusted directly, not a real CA chain).
 */
#ifndef HTTPS_CA_CERT_H
#define HTTPS_CA_CERT_H

static const unsigned char https_ca_cert_der[] = {{
{chr(10).join(lines)}
}};

static const unsigned int https_ca_cert_der_len = {len(data)};

#endif /* HTTPS_CA_CERT_H */
"""

open(header_path, "w").write(header)
print(f"  {len(data)} bytes DER -> {header_path}")
PYEOF

echo "Done. tools/certs/server.{crt,key} (PEM) + NetXDuo/App/https_ca_cert.h"
